### ISSUE TITLE
Stock is not updated for out-of-stock products with specific store settings

### ISSUE THREAD

**Issue by Saggre** [PostiDigital/woocommerce-warehouse-plugin#11]
The plugin uses `WC_Product_Variable::get_available_variations()` to determine the variations that need to be processed.

For instance, here:

https://github.com/PostiDigital/woocommerce-warehouse-plugin/blob/096177d65a6f0fcc9b4c84168fe4d47b115b06e3/classes/class-product.php#L459

However, when the store is set to hide out-of-stock products, [those products are ignored altogether](https://github.com/woocommerce/woocommerce/blob/bff253d6dc822f8051be440e585b4856f857f8e2/plugins/woocommerce/includes/class-wc-product-variable.php#L317-L320).
This causes the warehouse plugin to not update stock for these products. The products will be stuck in an out-of-stock state.

```php
public function get_available_variations( $return = 'array' ) {
    ...
    foreach ( $variation_ids as $variation_id ) {
        if ( ! $variation || ! $variation->exists() || ( 'yes' === get_option( 'woocommerce_hide_out_of_stock_items' ) && ! $variation->is_in_stock() ) ) {
            continue;
        }
    }
    ...
}
```

**Comment by suhhomi1** [comment]
Hi, thanks for reporting and fixing the issue!
I would suggest to introduce get_available_variations into the plugin but without the 'woocommerce_hide_out_of_stock_items' and without return/cache logic. Not sure if WC_Product_Variation is needed, woo does get_available variation instead.

**Comment by Saggre** [comment]
@suhhomi1 Updated the PR
